SALT_SIZE = 16
IV_SIZE_GCM = 12
TAG_SIZE = 16
LENGTH_SIZE = 8

AES_KEY_SIZE_BYTES = 32
KEY_SIZE = 32  # Alias for compatibility with kdf.py

PBKDF2_ITERATIONS = 600000

METHOD_AES_GCM = 1
METHOD_HYBRID_RSA = 2

CURRENT_VERSION = 1

METHOD_MAP = {
    "aes": METHOD_AES_GCM,
    "hybrid": METHOD_HYBRID_RSA
}
